#ifndef MODELCOLUMNINDEXES
#define MODELCOLUMNINDEXES

#define PACKET_NUMBER_COLUMN_INDEX 0 // 界面数据包序号
#define TIME_RECIEVED_COLUMN_INDEX 1 // 数据包到达时间
#define SOURCE_ADDRESS_COLUMN_INDEX 2 // 源IP地址
#define DESTINATION_ADDRESS_COLUMN_INDEX 3 // 目的IP地址
#define BINARY_DATA_SIZE_COLUMN_INDEX 4 // 捕获的数据包大小
#define HIGHEST_LEVEL_PROTOCOL_COLUMN_INDEX 5 // 协议类型
#define INFORMATION_COLUMN_INDEX 6 // 数据包概要信息

#endif // MODELCOLUMNINDEXES